---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - p2ppolicies.starlingx.windriver.com
  resources:
  - p2psecuritypolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - p2ppolicies.starlingx.windriver.com
  resources:
  - p2psecuritypolicies/finalizers
  verbs:
  - update
- apiGroups:
  - p2ppolicies.starlingx.windriver.com
  resources:
  - p2psecuritypolicies/status
  verbs:
  - get
  - patch
  - update
